/* ===================================================
   PORTFOLIO DATA
   Hand-edited: titles, brands, descriptions, order.
   Media (video / preview / poster / size) is generated by
   `node scripts/encode.mjs` into src/media-manifest.json and
   uploaded to the media host (see docs/media.md).
   brand is optional — omit or set null to hide.
   =================================================== */

import manifest from './media-manifest.json';

// Dev serves media-out/ locally (see vite.config.js). Production uses the CDN.
export const MEDIA_BASE =
  import.meta.env.VITE_MEDIA_BASE ??
  (import.meta.env.DEV ? '/media/' : 'https://media.yosroffscript.me/');

function media(slug) {
  const m = manifest[slug];
  if (!m) throw new Error(`projects.js: no media-manifest entry for "${slug}" — run scripts/encode.mjs`);
  return {
    src: MEDIA_BASE + m.files.video,
    preview: MEDIA_BASE + m.files.preview,
    poster: MEDIA_BASE + m.files.poster,
    aspect: m.aspect,
    duration: m.duration,
  };
}

const ALL_CATEGORIES = [
  { id: 'fashion', label: 'Fashion', coverFrom: 'fashion-sakina' },
  { id: 'bts', label: 'BTS', coverFrom: 'bts-lail-fashion' },
  { id: 'events', label: 'Events', coverFrom: 'events-salata' },
  { id: 'fnb', label: 'F&B', coverFrom: null },
  { id: 'film', label: 'Film', coverFrom: 'film-the-hungary-experience' },
];

// Fill descriptions / brands as you like. Empty description hides the line.
const ENTRIES = [
  // Fashion
  { slug: 'fashion-casa-lila', category: 'fashion', title: 'Casa Lila' },
  { slug: 'fashion-sakina', category: 'fashion', title: 'Sakina' },
  { slug: 'fashion-worood', category: 'fashion', title: 'Worood' },
  { slug: 'fashion-shakti-the-brand-l', category: 'fashion', title: 'Shakti the Brand I', brand: 'Shakti' },
  { slug: 'fashion-shakti-the-brand-ll', category: 'fashion', title: 'Shakti the Brand II', brand: 'Shakti' },
  { slug: 'fashion-shakti-the-brand-lll', category: 'fashion', title: 'Shakti the Brand III', brand: 'Shakti' },
  { slug: 'fashion-l', category: 'fashion', title: 'Untitled I' },
  { slug: 'fashion-ll', category: 'fashion', title: 'Untitled II' },

  // BTS
  { slug: 'bts-lail-fashion', category: 'bts', title: 'Lail Fashion' },
  { slug: 'bts-bossa-nova', category: 'bts', title: 'Bossa Nova' },
  { slug: 'bts-jjs-designs', category: 'bts', title: 'JJ’s Designs' },
  { slug: 'bts-atm-production-in-your-shoe', category: 'bts', title: 'In Your Shoe', brand: 'ATM Production' },
  { slug: 'bts-atm-production-roaia', category: 'bts', title: 'Roaia', brand: 'ATM Production' },
  { slug: 'bts-atm-production-heddy-rassekh', category: 'bts', title: 'Heddy Rassekh', brand: 'ATM Production' },

  // Events
  { slug: 'events-salata', category: 'events', title: 'Salata' },
  { slug: 'events-knowledge-valley-schools', category: 'events', title: 'Knowledge Valley Schools' },
  { slug: 'events-edu-gate-must', category: 'events', title: 'EDU Gate', brand: 'MUST' },
  { slug: 'events-outing-worood', category: 'events', title: 'Outing', brand: 'Worood' },

  // Film
  { slug: 'film-the-hungary-experience', category: 'film', title: 'The Hungary Experience' },
];

export const VIDEOS = ENTRIES.map((e, i) => ({
  id: i + 1,
  brand: null,
  description: '',
  ...e,
  ...media(e.slug),
}));

// Categories with no videos are hidden everywhere (cards + footer filters).
export const CATEGORIES = ALL_CATEGORIES.filter((c) =>
  VIDEOS.some((v) => v.category === c.id)
).map((c) => {
  const cover = c.coverFrom ? media(c.coverFrom).poster : VIDEOS.find((v) => v.category === c.id).poster;
  return { id: c.id, label: c.label, cover };
});

export function getVideosByCategory(categoryId) {
  return VIDEOS.filter((v) => v.category === categoryId);
}

export function getCategory(categoryId) {
  return CATEGORIES.find((c) => c.id === categoryId) || null;
}

export function getVideo(videoId) {
  return VIDEOS.find((v) => v.id === Number(videoId)) || null;
}
